services:
  app:
    build: .
    ports:
      - "30006:30006"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - sertif-uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  sertif-uploads:
