services:
  app:
    build: .
    ports:
      - "30006:30006"
    environment:
      DATABASE_URL: "file:/app/data/dev.db"
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - sertif-data:/app/data
      - sertif-uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  sertif-data:
  sertif-uploads:
